### PR TITLE
feture and fix 

### LINKED ISSUE #3: connect pool not work, and every command was close connection
```go

// Do send and recv
func (c *Client) Do(args Values) (v Values, err0 error) {
	conn, err := c.GetConn()
	if err != nil {
		return nil, err
	}
	defer func() {
		if err0 != nil {          //       bad !!!! now every success command will  close/reconnect !
			c.pool.Put(conn)
		} else {
			conn.Close()
		}
	}()

	err = conn.Send(args)
	if err != nil {
		return nil, err
	}
	return conn.Recv()
}
```

### PR DESCRIPTION
**Pull request by RelicOfTesla**
support ignore not found error ; support connect/read/write timeout; fix #3 ;

### CODE REVIEW

**Comment by wzshiming** [comment]
https://github.com/wzshiming/ssdb/compare/master...wzshiming:RelicOfTesla/master

@RelicOfTesla 
For the results of increasing the order of keeping and ignoring errors, I changed it a bit, and you review it please.

**Comment by RelicOfTesla** [comment]
```go
s := db.Get("asdfasdfasdfasdfsdfasdf").String()
// s = "<nil>"  // !!
// I think  better than assign "" 
```

**Comment by wzshiming** [comment]
@RelicOfTesla Thanks, updated, any other suggestions?

**Comment by RelicOfTesla** [comment]
no suggestions, did you will merge to master branch?

**Comment by wzshiming** [comment]
Merged, released v0.3.0

**Comment by RelicOfTesla** [comment]
sorry ....  Recv must use SetReadDeadline, not SetWriteDeadline
```

// Recv receive	data
func (c *Conn) Recv() (Values, error) {
	if c.readWriteTimeout != 0 {
		if err := c.conn.SetReadDeadline(time.Now().Add(c.readWriteTimeout)); err == nil {
			defer func() {
				_ = c.conn.SetReadDeadline(zeroTime)
			}()
		}
	}
```

**Comment by wzshiming** [comment]
Maybe `SetDeadline` is better?

**Comment by RelicOfTesla** [comment]
same

**Comment by wzshiming** [comment]
updated v0.3.1

**Pull request merged**
